# -*- coding: utf-8 -*-
"""Sistemas_de_auditoria__de_recursos_corporativos

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/1oed_tUPjZF6RE88SJoAAhIheOG94Fzbd

**Sistema de Auditoria de Recursos Corporativos**

Vinicius Scherer Di Giorno
"""

import time
from functools import wraps


# DECORATOR DE AUDITORIA

def auditor(func):
    @wraps(func)
    def wrapper(*args, **kwargs):
        print("\n" + "=" * 50)
        print("INICIANDO AUDITORIA DE ORÇAMENTO")
        print("=" * 50)

        print(f"Argumentos posicionais (*args): {args}")
        print(f"Argumentos nomeados (**kwargs): {kwargs}")

        inicio = time.time()

        resultado = func(*args, **kwargs)

        fim = time.time()
        tempo_total = fim - inicio

        print("-" * 50)
        print(f"Tempo de execução: {tempo_total:.6f} segundos")
        print("=" * 50)

        return resultado

    return wrapper

# EMPRESA

empresa = {
    "Matriz": {
        "TI": {
            "Infraestrutura": 50000,
            "Desenvolvimento": {
                "Backend": 80000,
                "Frontend": 70000
            },
            "Seguranca": 40000
        },
        "RH": {
            "Recrutamento": 25000,
            "Treinamento": 15000
        },
        "Financeiro": {
            "Contabilidade": 30000,
            "Auditoria": 20000
        }
    },
    "Filial_SP": {
        "Comercial": {
            "Vendas": 60000,
            "Marketing": 35000
        },
        "Suporte": 20000
    }
}

# FUNÇÃO RECURSIVA

@auditor
def calcular_orcamento(estrutura, *departamentos_ignorados, **kwargs):
    """
    estrutura -> dicionário da empresa
    *departamentos_ignorados -> departamentos que não entrarão na soma
    **kwargs -> parâmetros extras
    """

    taxa_cambio = kwargs.get("taxa_cambio", 1)
    moeda_destino = kwargs.get("moeda_destino", "BRL")

    def somar(dados):
        total = 0

        # Percorre cada item do dicionário
        for chave, valor in dados.items():

            # Ignora departamentos especificados
            if chave in departamentos_ignorados:
                print(f"[IGNORADO] Departamento: {chave}")
                continue

            # Se for outro dicionário, continua recursivamente
            if isinstance(valor, dict):
                total += somar(valor)

            # Se for número, soma ao total
            elif isinstance(valor, (int, float)):
                total += valor

        return total

    total_final = somar(estrutura) * taxa_cambio

    print(f"\nMoeda destino: {moeda_destino}")
    print(f"Taxa de câmbio aplicada: {taxa_cambio}")

    return total_final


# EXECUÇÃO

resultado = calcular_orcamento(
    empresa,
    "RH",
    "Marketing",
    moeda_destino="BRL",
    taxa_cambio=5.20
)

print(f"\nORÇAMENTO TOTAL CONVERTIDO: R$ {resultado:,.2f}")